project/demandas/views.py
"""
.. topic:: Demandas (views)

    Compõe o trabalho diário da coordenação. Surgem na medida que as tarefas são executadas na coordenação.
    O técnico cria a demanda para si em função de uma solicitação superior, de um colega, vinda de fora ou até mesmo
    por iniciativa própria, quando se tratar de necessidade de trabalho.

    Uma demanda tem atributos que são registrados no momento de sua criação:

    * Processo SEI relacionado (obrigatório)
    * Tipo (obrigatório e conforme valores prédefinidos)
    * Atividade do plano de trabalho
    * Título
    * Descrição
    * Se necessita despacho/apreciação superior
    * Se está concluída ou em andamento

.. topic:: Ações relacionadas às demandas

    * Listar atividades do plano de trabalho: plano_trabalho
    * Atualizar atividade do plano de trabalho: update_plano_trabalho
    * Inserir atividade no plano de trabalho: cria_atividade
    * Deleta um tipo de demanda: delete_tipo_demanda
    * Listar tipos de demanda: lista_tipos
    * Atualizar tipos de demandas: tipos_update
    * Inserir novo tipo de demanda: cria_tipo_demanda
    * Inserir novo passo para um tipo de demanda: cria_passo_tipo
    * Atualizar um passo de um tipo de demanda: update_passo_tipo
    * Listar passos de um tipo de demanda: lista_passos_tipos
    * Criar demandas: cria_demanda
    * Confirma criação de demanda: confirma_cria_demanda
    * Ler demandas: demanda
    * Registrar data de verificação de uma demanda: verifica
    * Listar demandas: list_demandas
    * Lista demandas não concluídas - lista RDU: prioriza
    * Atualizar demandas: update_demanda
    * Transferir demanda: transfer_demanda
    * Avocar demanda: avocar_demanda
    * Admin altera data de conclusão: admin_altera_demanda
    * Remover demandas: delete_demanda
    * Procurar demandas: pesquisa_demanda
    * Lista resultado da procura: list_pesquisa
    * Registrar despachos: cria_despacho
    * Aferir demandas: afere_demanda
    * Registrar providências: cria_providencia
    * Resumo e estatísticas das demandas: demandas_resumo

"""

# views.py dentro da pasta demandas

from flask import render_template, url_for, flash, request, redirect, Blueprint, abort, send_from_directory
from flask_login import current_user, login_required
from flask_mail import Message
from threading import Thread
from sqlalchemy import or_, and_, func, cast, String, Integer
from sqlalchemy.sql import label
from sqlalchemy.orm import aliased
from sqlalchemy.sql.functions import coalesce
from project import db, mail, app
from project.models import Demanda, Providencia, Despacho, User, Tipos_Demanda, Log_Auto, Plano_Trabalho,\
                           Sistema, Ativ_Usu, Passos_Tipos, Msgs_Recebidas, Coords
from project.demandas.forms import DemandaForm1, DemandaForm, Demanda_ATU_Form, DespachoForm, ProvidenciaForm, PesquisaForm,\
                                   Tipos_DemandaForm, TransferDemandaForm, Admin_Altera_Demanda_Form, PesosForm, Afere_Demanda_Form,\
                                   Plano_TrabalhoForm, Pdf_Form, CoordForm, Passos_Tipos_Form
#from project.users.views import send_email, send_async_email
from datetime import datetime, date, timedelta
from fpdf import FPDF

import pickle
import os.path
import sys

from calendar import monthrange

demandas = Blueprint("demandas",__name__,
                        template_folder='templates/demandas')

# helper function para envio de email em outra thread
def send_async_email(msg):
    """+--------------------------------------------------------------------------------------+
       |Executa o envio de e-mails de forma assíncrona.                                       |
       +--------------------------------------------------------------------------------------+
    """
    with app.app_context():
        mail.send(msg)

# helper function para enviar e-mail
def send_email(subject, recipients, text_body, html_body):
    """+--------------------------------------------------------------------------------------+
       |Envia e-mails.                                                                        |
       +--------------------------------------------------------------------------------------+
    """
    msg = Message(subject, recipients=recipients)
    msg.body = text_body
    msg.html = html_body
    thr = Thread(target=send_async_email, args=[msg])
    thr.start()

# função para registrar comits no log
def registra_log_auto(user_id,demanda_id,registro,atividade=None,duracao=0):
    """
    +---------------------------------------------------------------------------------------+
    |Função que registra ação do usuário na tabela log_auto.                                |
    |INPUT: id usúario, id demanda, registro                                                |
    |Os tipos de registro estão na tabela log_desc.                                         |
    +---------------------------------------------------------------------------------------+
    """

    reg_log = Log_Auto(data_hora   = datetime.now(),
                       user_id     = user_id,
                       demanda_id  = demanda_id,
                       registro    = registro,
                       atividade   = atividade,
                       duracao     = duracao)
    db.session.add(reg_log)
    db.session.commit()

    return

#
## lista plano de trabalho

@demandas.route('/plano_trabalho')
def plano_trabalho():
    """
    +---------------------------------------------------------------------------------------+
    |Apresenta o plano de trabalho da unidade do usuário logado.                            |
    |                                                                                       |
    +---------------------------------------------------------------------------------------+
    """

    unidade = current_user.coord

    # se unidade for pai, junta ela com seus filhos
    hierarquia = db.session.query(Coords.id).filter(Coords.id_pai == cast(unidade,Integer)).all()

    if hierarquia:
        l_unid = [str(f.id) for f in hierarquia]
        l_unid.append(unidade)
    else:
        l_unid = [unidade]

    user_titular = db.session.query(Ativ_Usu.atividade_id,
                                    User.username)\
                             .join(User, User.id == Ativ_Usu.user_id)\
                             .filter(Ativ_Usu.nivel == 'Titular')\
                             .subquery()
    #
    user_suplente = db.session.query(Ativ_Usu.atividade_id,
                                    User.username)\
                              .join(User, User.id == Ativ_Usu.user_id)\
                              .filter(Ativ_Usu.nivel == 'Suplente')\
                              .subquery()

    atividades = db.session.query(Plano_Trabalho.id,
                                  Plano_Trabalho.atividade_sigla,
                                  Plano_Trabalho.atividade_desc,
                                  Plano_Trabalho.natureza,
                                  Plano_Trabalho.meta,
                                  label('titular',user_titular.c.username),
                                  label('suplente',user_suplente.c.username),
                                  Plano_Trabalho.situa,
                                  Plano_Trabalho.unidade,
                                  Coords.sigla)\
                           .outerjoin(user_titular, Plano_Trabalho.id == user_titular.c.atividade_id)\
                           .outerjoin(user_suplente, Plano_Trabalho.id == user_suplente.c.atividade_id)\
                           .join(Coords, Coords.id == cast(Plano_Trabalho.unidade, Integer))\
                           .filter(Plano_Trabalho.unidade.in_(l_unid))\
                           .order_by(Plano_Trabalho.atividade_sigla)\
                           .all()

    quantidade = len(atividades)


    return render_template('plano_trabalho.html', atividades = atividades, quantidade=quantidade)

#
### atualiza atividade no plano de trabalho

@demandas.route("/<int:id>/update_plano_trabalho", methods=['GET', 'POST'])
@login_required
def update_plano_trabalho(id):
    """
    +----------------------------------------------------------------------------------------------+
    |Permite atualizar as atividades cadastradas no plano de trabalho.                             |
    |                                                                                              |
    |Recebe o id da atividade no plano como parâmetro.                                             |
    +----------------------------------------------------------------------------------------------+
    """

    atividade = Plano_Trabalho.query.get_or_404(id)

    unidade = db.session.query(Coords.id,Coords.sigla).filter(Coords.id == int(current_user.coord)).first()

    # se unidade for pai, junta ela com seus filhos
    hierarquia = db.session.query(Coords.id,Coords.sigla).filter(Coords.id_pai == unidade.id).all()

    if hierarquia:
        l_unid = [(u.id,u.sigla) for u in hierarquia]
        l_unid.append(unidade)
    else:
        l_unid = [(unidade.id,unidade.sigla)]

    lista_unids = [(str(u[0]),u[1]) for u in l_unid]
    lista_unids.insert(0,('',''))

    form = Plano_TrabalhoForm()

    form.unidade.choices = lista_unids

    if form.validate_on_submit():

        atividade.atividade_sigla = form.atividade_sigla.data
        atividade.atividade_desc  = form.atividade_desc.data
        atividade.natureza        = form.natureza.data
        atividade.meta            = form.horas_semana.data
        atividade.situa           = form.situa.data
        atividade.unidade         = form.unidade.data

        db.session.commit()

        registra_log_auto(current_user.id,None,'Atividade atualizada no Plano de Trabalho.')

        flash('Atividade atualizada no Plano de Trabalho!')
        return redirect(url_for('demandas.plano_trabalho'))

    elif request.method == 'GET':

project/demandas/templates/demandas/add_demanda.html
{% extends "base.html" %}
{% block content %}
<div class="container">

  <div class="jumbotron">

  <h5>Registrar Demanda </h5>

  {% macro render_field(field,obr) %}
    {% if obr == True %}
      <dt>{{ field.label(class="form-control-label") }}<span class="text-danger font-weight-bold">*</span>
    {% else %}
      <dt>{{ field.label(class="form-control-label") }}
    {% endif %}
    <dd>{{ field(**kwargs)|safe }}
    {% if field.errors %}
      <ul class=errors>
      {% for error in field.errors %}
        <li><span class="text-danger font-weight-bold">{{ error }}</span></li>
      {% endfor %}
      </ul>
    {% endif %}
    </dd>
  {% endmacro %}


  <form class="form-group" method='POST'>
    {{ form.hidden_tag() }}

    <div class="form-row">
      <div class="form-group col-3">
        <p></p>
        <p class="font-weight-bold">
          {% if '_' in sei %}
            Processo: {{ sei.replace('_','/')}}
          {% else %}
            Processo: {{ sei }}
          {% endif %}
        </p>
        <p class="font-weight-bold">Tipo: {{ tipo }}</p>
      </div>

      <div class="form-group col-2">
        {{ render_field(form.urgencia,class="form-control",obr=True) }}
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-4">
        {{ render_field(form.atividade,class="form-control",obr=True) }}
      </div>
    </div>

    <div class="form-group">
      {{ render_field(form.titulo,class="form-control",obr=True) }}
    </div>

    <div class="form-group">
      {{ render_field(form.desc,class="form-control",obr=True) }}
    </div>

    <div class="form-row">
      <div class="form-group col-3">
        <div class="form-check">
        {{ form.necessita_despacho(class="form-check-input") }}
        {{ form.necessita_despacho.label(class="form-check-label") }}
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="form-group col-3">
        {{ render_field(form.conclu,class="form-control",obr=False) }}
      </div>
    </div>

    <div class="form-group">
      {{ form.submit(class="btn btn-outline-primary") }}<span class="text-muted"> Atenção: campos marcados com * são obrigatórios.</span>
    </div>

  </div>

</div>
{% endblock %}

project/demandas/templates/demandas/add_demanda1.html
{% extends "base.html" %}
{% block content %}
<div class="container">

  <div class="jumbotron">

  <h5>Inserir/Atualizar Demanda (verificação) </h5>

  {% macro render_field(field,obr) %}
    {% if obr == True %}
      <dt>{{ field.label(class="form-control-label") }}<span class="text-danger font-weight-bold">*</span>
    {% else %}
      <dt>{{ field.label(class="form-control-label") }}
    {% endif %}
    <dd>{{ field(**kwargs)|safe }}
    {% if field.errors %}
      <ul class=errors>
      {% for error in field.errors %}
        <li><span class="text-danger font-weight-bold">{{ error }}</span></li>
      {% endfor %}
      </ul>
    {% endif %}
    </dd>
  {% endmacro %}


  <form class="form-group" method='POST'>
    {{ form.hidden_tag() }}

    <div class="form-row">
      <div class="form-group col-5">
        {{ render_field(form.sei,class="form-control",obr=True) }}
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-7">
        {{ render_field(form.tipo,class="form-control",obr=True) }}
      </div>
    </div>

    <div class="form-group">
      {{ form.submit(class="btn btn-outline-primary") }}<span class="text-muted"> Atenção: campos marcados com * são obrigatórios.</span>
    </div>

  </div>

</div>
{% endblock %}

project/demandas/templates/demandas/add_passo_tipo.html
{% extends "base.html" %}
{% block content %}
<div class="container">

<div class="jumbotron">
<h1>Inserir/Alterar Passo para {{ tipo.tipo }}</h1>

{% macro render_field(field,obr) %}
  {% if obr == True %}
    <dt>{{ field.label(class="form-control-label") }}<span class="text-danger font-weight-bold">*</span>
  {% else %}
    <dt>{{ field.label(class="form-control-label") }}
  {% endif %}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li><span class="text-danger font-weight-bold">{{ error }}</span></li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

<form class="needs-validation" method='POST' >
  {{ form.hidden_tag() }}

  <div class="form-group col-2">
    {% if form.ordem.data != None and form.ordem.data != '' %}
      <dt>{{ form.ordem.label }}</dt> <dd>{{ form.ordem(readonly=true) }}</dd>
    {% else %}
      {{ render_field(form.ordem,class="form-control",obr=True) }}
    {% endif %}
  </div>

  <div class="form-group col-3">
    {{ render_field(form.passo,class="form-control",obr=True) }}
  </div>

  <div class="form-group col-9">
    {{ render_field(form.desc,class="form-control",rows="5",obr=True) }}
  </div>

  <div class="form-group">
    {{ form.submit(class="btn btn-primary") }}
  </div>

</div>
</div>

{% endblock %}

project/demandas/templates/demandas/add_providencia.html
{% extends "base.html" %}
{% block content %}

<div class="container">

  <div class="jumbotron">

    <div class="row">
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Demanda {{post.id}}</h5>
              {% if titulo != None %}
                <h4>{{titulo}}</h4><br>
              {% endif %}

              <h5>Processo: {{post.sei}}</h5><br>

              <h5>Tipo:
              <a href="{{url_for('demandas.lista_passos_tipos', tipo_id=tipo_demanda_id)}}"><abbr title="Clique aqui para ver os passos."><b>{{tipo}}</b></a></h5>

              <h5>Descrição: {{desc}}</h5><br>

              <h5>Responsável: <b>{{post.author.username}}</b></h5><br>

              <h5>Registrada em: {{data.strftime('%x')}}</h5><br>

              {% if necessita_despacho == 0 %}
                <h4>Necessita despacho: Não</h4>
              {% else %}
                <h4 class="text-danger">Necessita despacho: Sim</h4>
              {% endif %}
              {% if post.necessita_despacho_cg == 0 %}
                <h4>Necessita despacho sup.: Não</h4>
              {% else %}
                <h4 class="text-info">Necessita despacho sup.: Sim</h4>
              {% endif %}
              {% if conclu == '0' %}
                <h4>Concluído: Não</h4>
              {% else %}
                <h4 class="text-success">Concluído: Sim</h4>
              {% endif %}
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h6 class="card-title">Providência</h6>
              <h4>Inserir Providência</h4>

              {% macro render_field(field,obr) %}
                {% if obr == True %}
                  <dt>{{ field.label(class="form-control-label") }}<span class="text-danger font-weight-bold">*</span>
                {% else %}
                  <dt>{{ field.label(class="form-control-label") }}
                {% endif %}
                <dd>{{ field(**kwargs)|safe }}
                {% if field.errors %}
                  <ul class=errors>
                  {% for error in field.errors %}
                    <li><span class="text-danger font-weight-bold">{{ error }}</span></li>
                  {% endfor %}
                  </ul>
                {% endif %}
                </dd>
              {% endmacro %}

              <form class="form-group" method='POST'>
                {{ form.hidden_tag() }}

                <div class="row">
                  <div class="col-5 px-md-2" >
                    {{ render_field(form.data_hora,class="form-control",obr=True) }}
                  </div>

                  <div class="col-4 px-md-3" >
                    {{ render_field(form.duracao,class="form-control" ,obr=True) }}
                  </div>
                </div>

                <div class="form-group">
                  {{ render_field(form.passo,class="form-control",obr=False) }}
                </div>

                <div class="form-group">
                  {{ render_field(form.texto,class="form-control form-control-lg", rows="3",obr=True) }}
                </div>

                <div class="row">
                  <div class="col-1">
                  </div>
                  <div class="form-check">
                    {{ form.necessita_despacho(class="form-check-input", type="checkbox") }}
                    {{ form.necessita_despacho.label(class="form-check-label") }}
                  </div>
                  <div class="col-1">
                  </div>
                  {% if current_user.id == demanda_user_id %}
                    <div class="form-check">
                      {{ render_field(form.conclu,class="form-control",obr=False) }}
                      <!-- {{ form.conclu(class="form-check-input", type="checkbox") }}
                      {{ form.conclu.label(class="form-check-label") }} -->
                    </div>
                  {% endif %}
                </div>

                <div class="form-group">
                  <br>
                  {{ form.submit(class="btn btn-outline-primary") }}<span class="text-muted"> Atenção: campos marcados com * são obrigatórios.</span>
                </div>
          </div>
        </div>
      </div>
    </div>


  </div>

</div>
{% endblock %}

project/demandas/templates/demandas/add_tipo.html
{% extends "base.html" %}
{% block content %}
<div class="container">

<div class="jumbotron">
<h2>Inserir/Alterar/Deletar Tipo de Demanda</h2>

{% macro render_field(field,obr) %}
  {% if obr == True %}
    <dt>{{ field.label(class="form-control-label") }}<span class="text-danger font-weight-bold">*</span>
  {% else %}
    <dt>{{ field.label(class="form-control-label") }}
  {% endif %}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li><span class="text-danger font-weight-bold">{{ error }}</span></li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

<form class="needs-validation" method='POST'>
  {{ form.hidden_tag() }}

  <div class="form-group col-5">
    {{ render_field(form.tipo,class="form-control",obr=True) }}
  </div>

  <div class="form-group col-2">
    {{ render_field(form.relevancia,class="form-control",obr=True) }}
  </div>


  <div class="row">
    <div class="form-group col-4">
      {{ form.submit(class="btn btn-outline-primary") }}
    </div>

    <div class="form-group col">
      {% if id != 0 %}
      <button type="button" class="btn btn-outline-danger" data-toggle='modal' data-target='#del_modal'>Excluir</button>
      {% endif %}
    </div>
  </div>
</form>

</div>
</div>

{# modal para deleção de tipo de demanda #}

  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="p-3 mb-2 bg-danger text-white">
        <h5 class="modal-title">Exluir Tipo de Demanda?</h5>
        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Deseja realmente excluir este tipo de demanda?</p>
        <p class="text-danger">ATENÇÃO!</p>
        <p class="text-danger">Caso haja demanda associada a este tipo, a deleção não será concretizada!</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>

        <form action="{{url_for('demandas.delete_tipo_demanda',id=id)}}" method="post">
          <input class="btn btn-danger" type="submit" name="" value="Excluir">
        </form>

      </div>
    </div>
  </div>
</div>


{% endblock %}

project/demandas/templates/demandas/admin_altera_demanda.html
{% extends "base.html" %}
{% block content %}
<div class="container">

  <div class="jumbotron">

  <h5>Altera data de conclusão da Demanda {{demanda_id}}</h5>

  {% macro render_field(field,obr) %}
    {% if obr == True %}
      <dt>{{ field.label(class="form-control-label") }}<span class="text-danger font-weight-bold">*</span>
    {% else %}
      <dt>{{ field.label(class="form-control-label") }}
    {% endif %}
    <dd>{{ field(**kwargs)|safe }}
    {% if field.errors %}
      <ul class=errors>
      {% for error in field.errors %}
        <li><span class="text-danger font-weight-bold">{{ error }}</span></li>
      {% endfor %}
      </ul>
    {% endif %}
    </dd>
  {% endmacro %}


  <form class="form-group" method='POST'>
    {{ form.hidden_tag() }}

    <div class="form-row">
      <div class="form-group col-3">
        {{ render_field(form.data_conclu,class="form-control",placeholder="dd/mm/aaaa",obr=True) }}
      </div>
    </div>

    <div class="form-group">
      {{ form.submit(class="btn btn-primary active") }}<span class="text-muted"> Atenção: campos marcados com * são obrigatórios.</span>
    </div>

  </div>

</div>
{% endblock %}

project/demandas/templates/demandas/atualiza_demanda.html
{% extends "base.html" %}
{% block content %}
<div class="container">

  <div class="jumbotron">

  <h5><b>Atualizar Demanda nº {{demanda_id}}</b></h5>

  {% macro render_field(field,obr) %}
    {% if obr == True %}
      <dt>{{ field.label(class="form-control-label") }}<span class="text-danger font-weight-bold">*</span>
    {% else %}
      <dt>{{ field.label(class="form-control-label") }}
    {% endif %}
    <dd>{{ field(**kwargs)|safe }}
    {% if field.errors %}
      <ul class=errors>
      {% for error in field.errors %}
        <li><span class="text-danger font-weight-bold">{{ error }}</span></li>
      {% endfor %}
      </ul>
    {% endif %}
    </dd>
  {% endmacro %}


  <form class="form-group" method='POST'>
    {{ form.hidden_tag() }}

    <div class="form-row">
      <div class="form-group col-5">
        {{ render_field(form.sei,class="form-control",obr=True) }}
      </div>
      <div class="form-group col-3">
        {{ render_field(form.tipo,class="form-control",obr=True) }}
      </div>

    </div>

    <div class="form-row">
      <div class="form-group col-2">
        {{ render_field(form.urgencia,class="form-control",obr=True) }}
      </div>
      <div class="form-group col-6">
        {{ render_field(form.atividade,class="form-control",obr=True) }}
      </div>
    </div>

    <div class="form-group">
      {{ render_field(form.titulo,class="form-control",obr=True) }}
    </div>

    <div class="form-group">
      {{ render_field(form.desc,class="form-control",obr=True) }}
    </div>

    <div class="form-row">
      <div class="form-group col-2">
        <div class="form-check">
          {{ form.tipo_despacho.label(class="form-check-label") }}
        </div>
      </div>
      <div class="form-group col-4">
        <div class="form-check form-check-inline">
          {{ form.tipo_despacho(class="form-check-input") }}
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="form-group col-3">
        {{ render_field(form.conclu,class="form-control",obr=False) }}
      </div>
    </div>

    <div class="form-group">
      {{ form.submit(class="btn btn-primary active") }}<span class="text-muted"> Atenção: campos marcados com * são obrigatórios.</span>
    </div>

  </div>

</div>
{% endblock %}

project/demandas/templates/demandas/email_demanda_transf.html
  <b>Aviso de transferência de demanda</b>
  <br>
  <br>
  <b>Título:</b> {{ titulo }}
  <br>
  <br>
  <b>{{ user }}</b>
  transferiu a demanda
  <b>{{ demanda }}</b>
  para
  <b>{{ receb }}</b>
  <br>
  <br>
  <b>** Favor verificar. Obrigado! **</b>
  <br>
  <br>
  --
  <br>
  {{sistema}}

project/demandas/templates/demandas/plano_trabalho.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h5><b>Plano de Trabalho (Atividades)</b></h5>

  {% if current_user.is_authenticated %}
    {% if current_user.despacha == 1 or current_user.role[0:5] == "admin" %}
      <div>
        <a href="{{url_for('demandas.cria_atividade')}}" class="btn btn-outline-primary" role="button" aria-pressed="true">Inserir Atividade</a>
        <small class="form-text text-muted">Ou clique em um número de sequência para alterar atividade existente.</small>
      </div>
    {% endif %}
  {% endif %}
  <br>

<caption>
  <div class="row">
      <div class="col">
        <p>Lista das <span class="badge badge-pill badge-primary">{{quantidade}}</span> atividades.</p>
      </div>
  </div>
</caption>

<div class="container" style="overflow-y: auto; height:400px">

  <table id="table"
        data-toggle="table"
        data-show-search-clear-button="true"
        data-sortable="true"
        classes="table-sm"
        data-show-columns="true"
        data-show-columns-toggle-all="true"
        class="table table-striped table-hover table-sm">
    <caption>Plano de Trabalho</caption>
    <thead>
      <tr>
        <th scope="col"><p align = "center">#</p></th>
        <th scope="col" data-sortable="true"><p align = "center">Unidade</p></th>
        <th scope="col" data-sortable="true"><p align = "center">Sigla</p></th>
        <th scope="col" data-sortable="true"><p align = "center">Descrição</p></th>
        <th scope="col" data-sortable="true"><p align = "center">Natureza</p></th>
        <th scope="col" data-sortable="true"><p align = "center">Meta (h/sem.)</p></th>
        <th scope="col" data-sortable="true"><p align = "center">Titular</p></th>
        <th scope="col" data-sortable="true"><p align = "center">Suplente</p></th>
      </tr>
    </thead>
    <tbody>

      {% for atividade in atividades %}

      <tr>
        {% if current_user.despacha == 1 or current_user.role[0:5] == "admin" %}
          <th scope="row"><p align = "center"><a href="{{url_for('demandas.update_plano_trabalho', id=atividade.id)}}"> {{atividades.index(atividade) + 1}} </a></p></th>
        {% else %}
          <th scope="row"><p align = "center"> {{atividades.index(atividade) + 1}} </p></th>
        {% endif %}
        <td><p align = "center"> {{atividade.sigla}} </p></td>
        <td><p align = "center"> {{atividade.atividade_sigla}} </p></td>
        <td><p align = "left">   {{atividade.atividade_desc}} </p></td>
        <td><p align = "center"> {{atividade.natureza}} </p></td>
        <td><p align = "center"> {{atividade.meta}} </p></td>
        {% if atividade.status != 'Desativada' %}
          {% if atividade.titular == None %}
            <td><p align = "center"> Não há </p></td>
          {% else %}
            <td><p align = "center"> {{atividade.titular}} </p></td>
          {% endif %}
          {% if atividade.suplente == None %}
            <td><p align = "center"> Não há </p></td>
          {% else %}
            <td><p align = "center"> {{atividade.suplente}} </p></td>
          {% endif %}
        {% else %}
          <td><p align = "center"> DESATIVADA </p></td>
          <td><p align = "center"> DESATIVADA </p></td>
        {% endif %}
      </tr>

      {% endfor %}

    </tbody>
  </table>

</div>

</div>
{% endblock %}