project/objetos/views.py
"""
.. topic:: objetos (views)

    Os objetos são objetos que a coordenação necessita de um registro mínimo para referência em demandas.

    Um objeto tem atributos que são registrados no momento de sua criação. Todos são obrigatórios:

    * Título
    * Contraparte
    * Número do processo SEI
    * Data de início
    * Data de término
    * Valor associado
    * Descrição

.. topic:: Ações relacionadas aos objetos

    * Listar objetos: lista_objetos
    * Atualizar/visualizar dados de um objeto: update
    * Registrar um objeto no sistema: cria_objeto
    * Listar demandas de um determinado objeto: objeto_demandas

"""

# views.py na pasta objetos

from flask import render_template,url_for,flash, redirect,request,Blueprint, abort
from flask_login import current_user,login_required
from sqlalchemy import func, distinct, cast, Integer
from sqlalchemy.sql import label
from project import db
from project.models import User, Demanda, Coords, Objeto
from project.objetos.forms import objetoForm, ListaForm
from project.demandas.views import registra_log_auto

import locale
from datetime import datetime, date
from dateutil.rrule import rrule, MONTHLY

objetos = Blueprint('objetos',__name__,
                            template_folder='templates/objetos')

#
def none_0(a):
    '''
    DOCSTRING: Transforma None em 0.
    INPUT: campo a ser trandormado.
    OUTPUT: 0, se a entrada for None, caso contrário, a entrada.
    '''
    if a == None:
        a = 0
    return a


@objetos.route('/<lista>/<coord>/lista_objetos', methods=['GET', 'POST'])
def lista_objetos(lista,coord):
    """
    +---------------------------------------------------------------------------------------+
    |Apresenta uma lista dos objetos.                                                       |
    |                                                                                       |
    |O objeto é algo tratado pela área técnica que justifica um registro específico.        |
    |Um contratao é um exemplo de objeto.                                                   |
    |                                                                                       |
    |No topo da tela há a opção de se inserir um novo objeto e o número sequencial          |
    |de cada objeto (#), ao ser clicado, permite que seus dados possam ser editados.        |
    |                                                                                       |
    +---------------------------------------------------------------------------------------+
    """

    hoje = datetime.today().date()

    form = ListaForm()
    
    coords = db.session.query(Coords.id,Coords.sigla)\
                       .order_by(Coords.sigla).all()
    lista_coords = [(c.id,c.sigla) for c in coords]
    lista_coords.insert(0,('',''))
    
    form.coord.choices = lista_coords

    if form.validate_on_submit():

        coord = form.coord.data

        if coord == '' or coord == None:
            coord = '*'

        return redirect(url_for('objetos.lista_objetos',lista=lista,coord=coord))

    else:

        if coord == '*':

            form.coord.data = ''

            coordenacao = db.session.query(Coords.id,
                                           Coords.sigla)\
                                    .subquery()

        else:

            form.coord.data = coord

            coordenacao = db.session.query(Coords.id,
                                           Coords.sigla)\
                                    .filter(Coords.id == cast(coord,Integer))\
                                    .subquery()

        if lista == 'todos':
            objetos_v = db.session.query(Objeto.id,
                                         Objeto.coord,
                                         Objeto.nome,
                                         Objeto.contraparte,
                                         Objeto.sei,
                                         Objeto.descri,
                                         Objeto.data_inicio,
                                         Objeto.data_fim,
                                         Objeto.valor,
                                         coordenacao.c.sigla)\
                                  .join(coordenacao, coordenacao.c.id == cast(Objeto.coord,Integer))\
                                  .order_by(Objeto.nome).all()

        elif lista == 'em execução':
            objetos_v = db.session.query(Objeto.id,
                                              Objeto.coord,
                                              Objeto.nome,
                                              Objeto.contraparte,
                                              Objeto.sei,
                                              Objeto.descri,
                                              Objeto.data_inicio,
                                              Objeto.data_fim,
                                              Objeto.valor,
                                              coordenacao.c.sigla)\
                                       .join(coordenacao, coordenacao.c.id == cast(Objeto.coord,Integer))\
                                       .filter(Objeto.data_fim >= hoje,
                                               Objeto.data_inicio <= hoje)\
                                       .order_by(Objeto.data_fim,Objeto.nome).all()

        quantidade = len(objetos_v)

        return render_template('lista_objetos.html', objetos=objetos_v,quantidade=quantidade,lista=lista,form=form)


### ATUALIZAR objeto

@objetos.route("/<int:objeto_id>/update", methods=['GET', 'POST'])
@login_required
def update(objeto_id):
    """
    +---------------------------------------------------------------------------------------+
    |Permite atualizar os dados de um objeto selecionado na tela de consulta.          |
    |                                                                                       |
    |Recebe o ID do objeto como parâmetro.                                             |
    +---------------------------------------------------------------------------------------+
    """

    objeto = Objeto.query.get_or_404(objeto_id)

    form = objetoForm()

    if form.validate_on_submit():

        objeto.coord       = form.coord.data
        objeto.nome        = form.nome.data
        objeto.sei         = form.sei.data
        objeto.contraparte = form.contraparte.data
        objeto.data_inicio = form.data_inicio.data
        objeto.data_fim    = form.data_fim.data
        objeto.valor       = float(form.valor.data.replace('.','').replace(',','.'))
        objeto.descri      = form.descri.data

        db.session.commit()

        registra_log_auto(current_user.id,None,'itm')

        flash('objeto atualizado!')
        return redirect(url_for('objetos.lista_objetos',lista='todos',coord = '*'))
    # traz a informação atual do objeto
    elif request.method == 'GET':
        form.coord.data        = objeto.coord
        form.nome.data         = objeto.nome
        form.sei.data          = objeto.sei
        form.contraparte.data  = objeto.contraparte
        form.data_inicio.data  = objeto.data_inicio
        form.data_fim.data     = objeto.data_fim
        form.valor.data        = locale.currency( objeto.valor, symbol=False, grouping = True )
        form.descri.data       = objeto.descri

    return render_template('add_objeto.html', title='Update',
                           form=form, id=objeto_id)

### CRIAR objeto

@objetos.route("/criar", methods=['GET', 'POST'])
@login_required
def cria_objeto():
    """
    +---------------------------------------------------------------------------------------+
    |Permite registrar os dados de um objeto.                                               |
    +---------------------------------------------------------------------------------------+
    """

    form = objetoForm()
    
    coords = db.session.query(Coords.id,Coords.sigla)\
                       .order_by(Coords.sigla).all()
    lista_coords = [(c.id,c.sigla) for c in coords]
    lista_coords.insert(0,('',''))
    
    form.coord.choices = lista_coords

    if form.validate_on_submit():
        objeto = Objeto(coord       = form.coord.data,
                        nome        = form.nome.data,
                        contraparte = form.contraparte.data,
                        sei         = form.sei.data,
                        data_inicio = form.data_inicio.data,
                        data_fim    = form.data_fim.data,
                        valor       = float(form.valor.data.replace('.','').replace(',','.')),
                        descri      = form.descri.data)

        db.session.add(objeto)
        db.session.commit()

        registra_log_auto(current_user.id,None,'Objeto registrado!')

        flash('Objeto registrado!')
        return redirect(url_for('objetos.lista_objetos',lista='todos',coord = '*'))


    return render_template('add_objeto.html', form=form, id=0 )


# lista das demandas relacionadas a um objeto

@objetos.route('/<objeto_id>/objeto_demandas')
def objeto_demandas (objeto_id):
    """+--------------------------------------------------------------------------------------+
       |Mostra as demandas relacionadas a um objeto quando seu NUP é selecionado em uma  |
       |lista de objetos.                                                                |
       |Recebe o id do objeto como parâmetro.                                            |
       +--------------------------------------------------------------------------------------+
    """

    objeto_SEI = db.session.query(Objeto.sei,Objeto.nome).filter_by(id=objeto_id).first()

    SEI = objeto_SEI.sei
    SEI_s = str(SEI).replace('/','_')

    demandas_count = Demanda.query.filter(Demanda.sei.like('%'+SEI+'%')).count()

    demandas = Demanda.query.filter(Demanda.sei.like('%'+SEI+'%'))\
                            .order_by(Demanda.data.desc()).all()

    autores=[]
    for demanda in demandas:

project/objetos/templates/objetos/add_objeto.html
{% extends "base.html" %}
{% block content %}
<div class="container">

  <div class="jumbotron">
    <h1>Inserir/Alterar/Visualizar Objeto</h1>

    {% macro render_field(field,obr) %}
      {% if obr == True %}
        <dt>{{ field.label(class="form-control-label") }}<span class="text-danger font-weight-bold">*</span>
      {% else %}
        <dt>{{ field.label(class="form-control-label") }}
      {% endif %}
      <dd>{{ field(**kwargs)|safe }}
      {% if field.errors %}
        <ul class=errors>
        {% for error in field.errors %}
          <li><span class="text-danger font-weight-bold">{{ error }}</span></li>
        {% endfor %}
        </ul>
      {% endif %}
      </dd>
    {% endmacro %}

    <form action="" method='POST' class="form" role="form">
      {{ form.hidden_tag() }}

      <div class="form-row">
        <div class="col-3">
          <div class="form-group">
            {{ render_field(form.coord,class="form-control",obr=True) }}
          </div>
        </div>
        <div class="col-4">
          <div class="form-group">
            {{ render_field(form.sei,class="form-control", placeholder="Entre com o NUP",obr=True) }}
          </div>
        </div>
      </div>

      <div class="form-row">
        <div class="col">
          <div class="form-group">
            {{ render_field(form.nome,class="form-control",obr=True) }}
          </div>
        </div>
      </div>

      <div class="form-row">
        <div class="col">
          <div class="form-group">
            {{ render_field(form.descri,class="form-control",obr=True) }}
          </div>
        </div>
      </div>

      <div class="form-row">
        <div class="col-3">
          <div class="form-group">
            {{ render_field(form.data_inicio,class="form-control", placeholder="dd/mm/aaaa",obr=False) }}
          </div>
        </div>
        <div class="col-3">
          <div class="form-group">
            {{ render_field(form.data_fim,class="form-control", placeholder="dd/mm/aaaa",obr=False) }}
          </div>
        </div>
      </div>

      <div class="form-row">
        <div class="col-4">
          <div class="form-group">
            {{ render_field(form.valor,class="form-control",placeholder="Somente número",obr=False) }}
          </div>
        </div>
      </div>


      <div class="form-row">
        <div class="form-group col-9">
          {{ form.submit(class="btn btn-primary") }}<span class="text-muted"> Atenção: campos marcados com * são obrigatórios.</span>
        </div>
        {% if id != 0 %}
          <div class="form-group col-2">
            <button type="button" class="btn btn-danger" data-toggle='modal' data-target='#del_modal'>Excluir</button>
          </div>
        {% endif %}
      </div>

    </form>

  </div>
</div>

{# modal para deleção de objeto #}

  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="p-3 mb-2 bg-danger text-white">
        <h5 class="modal-title">Exluir objeto?</h5>
        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Deseja realmente excluir este objeto?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>

        <form action="{{url_for('objetos.delete_objeto',objeto_id=id)}}" method="post">
          <input class="btn btn-danger" type="submit" name="" value="Excluir">
        </form>

      </div>
    </div>
  </div>
</div>

{% endblock %}

project/objetos/templates/objetos/lista_objetos.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
<h5>Lista de Objetos</h5>

  {% if current_user.is_authenticated %}
    <div>
      <div class="row">
        <div class="col-1">
          <a href="{{url_for('objetos.cria_objeto')}}" class="btn btn-primary active" role="button" aria-pressed="true">Inserir novo</a>
        </div>
        <div class="col">
          <small class="form-text text-muted">Ou clique em um número de sequência para alterar dados do respectivo objeto.</small>
        </div>

  {% endif %}
        <div class="col">
          <form class="form-group" method='POST'>
            {{ form.hidden_tag() }}
              <div class="row">
                <div class="col">
                  {{ form.coord(class="form-control form-control-sm") }}
                </div>
                <div class="col">
                  {{ form.submit(class="btn btn-outline-primary btn-sm") }}
                </div>
              </div>
          </div>
      </div>
<br>

<caption>
  <div class="row">
      <div class="col">
        <p>Lista com <span class="badge badge-pill badge-primary">{{quantidade}}</span>
          <span class="font-weight-bold">Objeto(s)</span> cadastrado(s)
          {% if lista == 'todos' %}
            <span class="text-info font-weight-bold">(todos)</span>
          {% endif %}
          {% if lista == 'em execução' %}
            <span class="text-info font-weight-bold">(vigentes)</span>
          {% endif %}
      </p>
      </div>

  </div>
</caption>

  <table class="table table-striped table-hover table-sm">
    <caption>objetos</caption>
    <thead>
      <tr>
        <th scope="col"><p align = "center">#</p></th>
        <th scope="col"><p align = "center">Unidade</p></th>
        <th scope="col"><p align = "center">Título</p></th>
        <!-- <th scope="col"><p align = "center">Contraparte</p></th> -->
        <th scope="col"><p align = "center">Processo</p></th>
        <th scope="col"><p align = "center">Início</p></th>
        <th scope="col"><p align = "center">Término</p></th>
        <th scope="col"><p align = "center">Valor</p></th>

      </tr>
    </thead>
    <tbody>
      {% for objeto in objetos %}

      <tr>
        <th scope="row"><p align = "center">
          {% if (objetos.index(objeto) + 1) <= quantidade %}
            <a href="{{url_for('objetos.update', objeto_id=objeto[0])}}"><abbr title="Clique aqui atualizar">{{objetos.index(objeto) + 1}}</abbr></a>
          {% endif %}
        </p></th>
        <td><p align = "center"><small> {{objeto.sigla}}</small></p></td>
        <td><p align = "center"><small> {{objeto.nome}}</small></p></td>
        <!-- <td><p align = "center"><small> {{objeto[3]}}</small></p></td> -->
        {% if objeto.sei != None%}
          <td><p align = "center"> <a href="{{url_for('objetos.objeto_demandas', objeto_id=objeto[0])}}"><abbr title="Clique aqui para ver demandas deste objeto"><small> {{objeto.sei}} </small></abbr></a> </p></td>
        {% else %}
          <td><p align = "center"><small> {{objeto.sei}}</small></p></td>
        {% endif %}
        <td>
          <p align = "center">
            <small>
                {% if objeto.data_inicio %}
                  {{objeto.data_inicio.strftime('%d/%m/%Y')}}
                {% else %}
                  N.I.
                {% endif %}  
              </small>
          </p>
        </td>
        <td>
          <p align = "center">
            <small>
                {% if objeto.data_fim %}
                  {{objeto.data_fim.strftime('%d/%m/%Y')}}
                {% else %}
                  N.I.
                {% endif %}  
              </small>
          </p>
        </td>
        <td><p align = "center"><small> {{objeto.valor|converte_para_real}}</small></p></td>
      </tr>

      {% endfor %}
    </tbody>
  </table>

</div>

{% endblock %}